services:
  - type: web
    name: learn-english-backend
    env: node
    plan: starter
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 20
